# require 'webpack_integration'
module WebpackIntergration

  # @example
  #   WebpackIntergration.script_for('clients')
  def self.script_for(bundle)
    path = Rails.root.join('app', 'views', 'webpack-assets.json') # This is the file generated by the plug-in
    file = File.read(path)
    json = JSON.parse(file)
    json[bundle]
  end


  def self.generate_manifest
    res = {}
    Dir['public/webpack/**/**/**'].each do |f|
      next if File.directory?(f)
      key      = f.gsub('public/webpack/', '')
      key      = key.gsub(/-[a-f\d]*(\.)/, '.')
      value    = f.sub('public', '')
      res[key] = value
    end
  end
end
